FROM adoptopenjdk/openjdk11:alpine

RUN apk update
RUN addgroup -S spring && adduser -S spring -G spring

USER spring:spring
ARG JAR_FILE=./target/*.jar

COPY ${JAR_FILE} discovery.jar

ENTRYPOINT ["java","-jar","/discovery.jar"]