server:
  port: ${ENV_PORT:8888}

spring:
  application:
    name: 'config-server'
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: /opt/app/conf

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${ENV_DISCOVERY_SERVER}:${ENV_DISCOVERY_PORT}/eureka/
