server:
  port: ${ENV_HOST_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: /opt/app/conf
  
eureka:
  client:
    service-url:
      defaultZone: http://${ENV_DISCOVERY_SERVER}:${ENV_DISCOVERY_PORT}/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${random.int}
