server:
  port: ${ENV_PORT:8888}

spring:
  application:
    name: 'config-server'
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: /opt/app/conf
