server:
  port: ${ENV_PORT:8761}
  
eureka:
  instance:
    hostname: ${ENV_HOST:discovery}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${ENV_PORT}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
