server:
  port: ${ENV_HOST_PORT:8761}

spring:
  application:
    name: discovery

eureka:
  instance:
    hostname: ${ENV_HOST_NAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
